version: '3.8'

services:
  flask-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: flask-app
    depends_on:
      - mongo
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    volumes:
      - ./app:/app    

  nextjs-frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: nextjs-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://flask-app:5000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NEXT_DISABLE_TURBOPACK=true
    depends_on:
      - flask-app
    networks:
      - app-network
    command: ["sh", "-c", "npm run dev"]
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules

  mongo:
    image: mongo:5.0.30
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    container_name: mongo
    networks:
      - app-network

volumes:
  mongo-data:
  node_modules:

networks:
  app-network:
    driver: bridge
